version: "1.1"
name: ""
"on":
  push:
    branches:
      - master
      - release/*
    tags:
      - v*
stages:
  - stage:
      - git-checkout:
          alias: erda-analyzer
          description: 代码仓库克隆
          params:
            depth: 1
  - stage:
      - extract-repo-version:
          alias: extract-repo-version
          description: 从 git 代码仓库中解析提交信息，生成仓库版本
          params:
            git_dir: ${{ dirs.erda-analyzer }}
  - stage:
      - dockerfile:
          alias: build-metrics
          description: 针对自定义 dockerfile 打包，产出可运行镜像
          version: "1.0"
          params:
            build_args:
              APP: analyzer-metrics
            image:
              name: erda-analyzer-metrics
              tag: ${{ outputs.extract-repo-version.image_tag }}
            path: Dockerfile
            registry:
              password: ${{ configs.docker_registry_password }}
              url: ${{ configs.docker_registry }}
              username: ${{ configs.docker_registry_username }}
            workdir: ${{ dirs.erda-analyzer }}
          resources:
            cpu: 2
            mem: 2048
      - dockerfile:
          alias: build-alert
          description: 针对自定义 dockerfile 打包，产出可运行镜像
          version: "1.0"
          params:
            build_args:
              APP: analyzer-alert
            image:
              name: erda-analyzer-alert
              tag: ${{ outputs.extract-repo-version.image_tag }}
            path: Dockerfile
            registry:
              password: ${{ configs.docker_registry_password }}
              url: ${{ configs.docker_registry }}
              username: ${{ configs.docker_registry_username }}
            workdir: ${{ dirs.erda-analyzer }}
          resources:
            cpu: 2
            mem: 2048
      - dockerfile:
          alias: build-error-insight
          description: 针对自定义 dockerfile 打包，产出可运行镜像
          version: "1.0"
          params:
            build_args:
              APP: analyzer-error-insight
            image:
              name: erda-analyzer-error-insight
              tag: ${{ outputs.extract-repo-version.image_tag }}
            path: Dockerfile
            registry:
              password: ${{ configs.docker_registry_password }}
              url: ${{ configs.docker_registry }}
              username: ${{ configs.docker_registry_username }}
            workdir: ${{ dirs.erda-analyzer }}
          resources:
            cpu: 2
            mem: 2048
      - dockerfile:
          alias: build-tracing
          description: 针对自定义 dockerfile 打包，产出可运行镜像
          version: "1.0"
          params:
            build_args:
              APP: analyzer-tracing
            image:
              name: erda-analyzer-tracing
              tag: ${{ outputs.extract-repo-version.image_tag }}
            path: Dockerfile
            registry:
              password: ${{ configs.docker_registry_password }}
              url: ${{ configs.docker_registry }}
              username: ${{ configs.docker_registry_username }}
            workdir: ${{ dirs.erda-analyzer }}
          resources:
            cpu: 2
            mem: 2048
  - stage:
      - release:
          alias: release-erda-analyzer
          description: 用于打包完成时，向dicehub 提交完整可部署的dice.yml。用户若没在pipeline.yml里定义该action，CI会自动在pipeline.yml里插入该action
          params:
            check_diceyml: false
            dice_yml: ${erda-analyzer}/erda.yml
            image:
              analyzer-alert: ${{ outputs.build-alert.image }}
              analyzer-alert-task: ${{ outputs.build-alert.image }}
              analyzer-error-insight: ${{ outputs.build-error-insight.image }}
              analyzer-error-insight-task: ${{ outputs.build-error-insight.image }}
              analyzer-metrics: ${{ outputs.build-metrics.image }}
              analyzer-metrics-task: ${{ outputs.build-metrics.image }}
              analyzer-tracing: ${{ outputs.build-tracing.image }}
              analyzer-tracing-task: ${{ outputs.build-tracing.image }}
            tag_version: ${{ outputs.extract-repo-version.version }}
