version: "1.1"

on:
  push:
    branches:
      - release/*
    tags:
      - v*

stages:
  - stage:
      - git-checkout:
          alias: erda-analyzer
          params:
            depth: 1
  - stage:
      - extract-repo-version:
          params:
            git_dir: ${{ dirs.erda-analyzer }}
  - stage:
      - custom-script:
          alias: build-metrics
          commands:
            - cd ${erda-analyzer}
            - ./build.sh analyzer-metrics
          resources:
            cpu: 2
            mem: 2048
      - custom-script:
          alias: build-alert
          commands:
            - cd ${erda-analyzer}
            - ./build.sh analyzer-alert
          resources:
            cpu: 2
            mem: 2048
      - custom-script:
          alias: build-error-insight
          commands:
            - cd ${erda-analyzer}
            - ./build.sh analyzer-error-insight
          resources:
            cpu: 2
            mem: 2048
      - custom-script:
          alias: build-tracing
          commands:
            - cd ${erda-analyzer}
            - ./build.sh analyzer-tracing
          resources:
            cpu: 2
            mem: 2048
  - stage:
      - release:
          alias: release-erda-analyzer
          params:
            check_diceyml: false
            dice_yml: ${erda-analyzer}/erda.yml
            image:
              analyzer-alert: ${{ outputs.build-alert.image }}
              analyzer-alert-task: ${{ outputs.build-alert.image }}
              analyzer-error-insight: ${{ outputs.build-error-insight.image }}
              analyzer-error-insight-task: ${{ outputs.build-error-insight.image }}
              analyzer-metrics: ${{ outputs.build-metrics.image }}
              analyzer-metrics-task: ${{ outputs.build-metrics.image }}
              analyzer-tracing: ${{ outputs.build-tracing.image }}
              analyzer-tracing-task: ${{ outputs.build-tracing.image }}
